language: php

php:
- 7.2

before_install:
- composer global require hirak/prestissimo

install:
- composer install

before_script:
- phpenv config-rm xdebug.ini

script:
- composer run lint
- bin/sync

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
