name: ci

on: [ push, pull_request, workflow_dispatch ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.7.0
    with:
     php-version: 7.4
  - run: composer install
  - run: composer run lint
 sync:
  needs: lint
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Set up PHP 7.4
    uses: shivammathur/setup-php@2.7.0
    with:
     php-version: 7.4
  - run: composer install
  - run: bin/sync
    env:
     DB_URL: ${{ secrets.DB_URL }}
